" General settings

" !silent is used to suppress error messages if the config line
" references plugins/colorschemes that might be missing

" Disable Vi compatibility
set nocompatible

" Point to location of pathogen submodule (since it's not in .vim/autoload)
silent! runtime bundle/vim-pathogen/autoload/pathogen.vim
" Call pathogen plugin management
silent! call pathogen#infect()

set background=dark
colorscheme molokai     " Load color scheme. ir_black is pretty good too
syntax enable           " Enable syntax highlighting

set encoding=utf-8      " Character encoding
set ruler               " Show <line, column> in status bar
set number              " Show line numbers
set bs=2                " Let backspace key make deletions
set colorcolumn=80      " Mark the 80 column limit
set ls=2                " Show status bar even with 1 window
set tabpagemax=100      " Allow 100 tabs max
set cursorline          " Highlight current row
set winheight=50        " Window height for organizing multiple files
set cmdheight=3         " Command window height

" Search settings
set hlsearch            " Highlight search matches
set ignorecase          " Ignore search case..
set smartcase           " ..unless I use capitals in query

" Tab settings
set ts=2                " Tab size is 4 spaces
set sw=2                " Shift 4 spaces using V + < / V + >
set expandtab           " Use spaces instead of tabs

" Settings by filetype
filetype indent on      " Allow indent by filetype
filetype plugin on      " Allow loading plugins by filetype

autocmd FileType html
  \ setlocal shiftwidth=2 |
  \ setlocal tabstop=2
autocmd FileType coffee
  \ setlocal shiftwidth=2 |
  \ setlocal tabstop=2
autocmd FileType javascript
  \ setlocal shiftwidth=2 |
  \ setlocal tabstop=2
autocmd FileType css
  \ setlocal shiftwidth=2 |
  \ setlocal tabstop=2
autocmd FileType less
  \ setlocal shiftwidth=2 |
  \ setlocal tabstop=2
autocmd FileType c
  \ setlocal shiftwidth=2 |
  \ setlocal tabstop=2

" Key mappings

" Custom plugins
nmap <F3> :execute "vimgrep /" . expand("<cword>") . "/j **" <Bar> cw<CR>

" Mocha tests
nnoremap <c-m> :<c-u>!mocha --reporter spec<cr>

" Tab Navigating
map <F5> gT
map <F6> gt
imap <F5> <Esc>gTi
imap <F6> <Esc>gti

map <Esc>1 1gt
map <Esc>2 2gt
map <Esc>3 3gt
map <Esc>4 4gt
map <Esc>5 5gt
map <Esc>6 6gt
map <Esc>7 7gt
map <Esc>8 8gt
map <Esc>9 9gt
map <Esc>0 10gt

" F2 makes pasting the clipboard preserve indentation
" F2 again turns that off.
nnoremap <F2> :set invpaste paste?<CR>
imap <F2> <C-O><F2>
set pastetoggle=<F2>

let g:netrw_liststyle=3
" let g:netrw_browse_split=4
let g:netrw_preview=1
" let g:netrw_winsize=30

map <c-l> <c-w>l
map <c-h> <c-w>h
map <c-j> <c-w>j

