" General settings

" !silent is used to suppress error messages if the config line
" references plugins/colorschemes that might be missing

" Disable vi compatibility
set nocompatible

" Point to location of pathogen submodule (since it's not in .vim/autoload)
silent! runtime bundle/vim-pathogen/autoload/pathogen.vim
" Call pathogen plugin management
silent! call pathogen#infect()

" Colors
set background=dark
colorscheme molokai     " Load color scheme. ir_black is pretty good too
syntax enable           " Enable syntax highlighting

" General
set encoding=utf-8      " Character encoding
set ruler               " Show <line, column> in status bar
set number              " Show line numbers
set bs=2                " Let backspace key make deletions
set colorcolumn=80      " Mark the 80 column limit
set ls=2                " Show status bar even with 1 window
set tabpagemax=100      " Allow 100 tabs max
set cursorline          " Highlight current row
set cmdheight=3         " Command window height
set wildmenu            " Command completion suggestions
set scrolloff=3         " Maintain more space around the cursor
set visualbell          " Disable the warning bell
set nowrap              " Don't wrap long lines

" Search settings
set hlsearch            " Highlight search matches
set ignorecase          " Ignore search case..
set smartcase           " ..unless I use capitals in query

" Tab settings
set ts=4                " Tab size is 4 spaces
set sw=4                " Shift 4 spaces using V + < / V + >
set expandtab           " Use spaces instead of tabs

" Settings by filetype
filetype indent on      " Allow indent by filetype
filetype plugin on      " Allow loading plugins by filetype

autocmd FileType html
  \ setlocal shiftwidth=2 |
  \ setlocal tabstop=2
autocmd FileType coffee
  \ setlocal shiftwidth=2 |
  \ setlocal tabstop=2
autocmd FileType javascript
  \ setlocal shiftwidth=2 |
  \ setlocal tabstop=2
autocmd FileType css
  \ setlocal shiftwidth=2 |
  \ setlocal tabstop=2
autocmd FileType less
  \ setlocal shiftwidth=2 |
  \ setlocal tabstop=2
autocmd FileType c
  \ setlocal shiftwidth=2 |
  \ setlocal tabstop=2

" Map leader
let mapleader = ','

" Find all occurrences of the word under the cursor
nmap <F3> :execute "vimgrep /" . expand("<cword>") . "/j **" <Bar> cw<CR>

" Tab Navigating
map <F5> gT
map <F6> gt
imap <F5> <Esc>gTi
imap <F6> <Esc>gti

" F2 makes pasting the clipboard preserve indentation
" F2 again turns that off.
nnoremap <F2> :set invpaste paste?<CR>
imap <F2> <C-O><F2>
set pastetoggle=<F2>

" Open NERDTree with Ctrl+o
map <c-o> :NERDTree<cr>

" Window navigation
map <c-l> <c-w>l
map <c-h> <c-w>h
map <c-j> <c-w>j
map <c-k> <c-w>k

" Source vimrc on file save
if has("autocmd")
  autocmd bufwritepost .vimrc source $MYVIMRC
endif
