" vimrc
" Author: Nick Thompson
" Source: https://github.com/nick-thompson/dotfiles

set nocompatible                " Disable vi compatibility
filetype off                    " Required by Vundle

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" Bundles
Bundle 'gmarik/vundle'

" Functional bundles
Bundle 'scrooloose/nerdtree'
Bundle 'airblade/vim-gitgutter'
Bundle 'bling/vim-airline'
Bundle 'nelstrom/vim-visual-star-search'
Bundle 'MartinLafreniere/vim-PairTools'

" Syntax bundles
Bundle 'pangloss/vim-javascript'
Bundle 'kchmck/vim-coffee-script'
Bundle 'groenewege/vim-less'
Bundle 'tpope/vim-markdown'
Bundle 'othree/html5.vim'
Bundle 'wavded/vim-stylus'
Bundle 'cakebaker/scss-syntax.vim'
Bundle 'guns/vim-clojure-static'
Bundle 'jordwalke/flatlandia'

" Settings
syntax on                       " Enable syntax highlighting
filetype plugin indent on       " Required by Vundle

colorscheme flatlandia

" General
set encoding=utf-8              " Character encoding
set ruler                       " Show <line, column> in status bar
set number                      " Show line numbers
set bs=2                        " Let backspace key make deletions
set ls=2                        " Show status bar even with 1 window
set tabpagemax=100              " Allow 100 tabs max
set cursorline                  " Highlight current row
set cmdheight=3                 " Command window height
set wildmenu                    " Command completion suggestions
set scrolloff=3                 " Maintain more space around the cursor
set visualbell                  " Disable the warning bell
set hlsearch                    " Highlight search matches
set ignorecase                  " Ignore search case..
set smartcase                   " ..unless I use capitals in query
set autoread                    " Auto read files on change
set colorcolumn=80              " Mark the 80 column limit
hi  ColorColumn guibg=#333436

" Tab settings
set ts=2                        " Tab size is 4 spaces
set sw=2                        " Shift 4 spaces using V + < / V + >
set expandtab                   " Use spaces instead of tabs

" Settings by filetype
filetype indent on              " Allow indent by filetype
filetype plugin on              " Allow loading plugins by filetype

autocmd FileType python
  \ setlocal sw=4 |
  \ setlocal ts=4
autocmd FileType sh
  \ setlocal sw=4 |
  \ setlocal ts=4

" NERDTree
let NERDTreeQuitOnOpen = 1

" Key mappings
let mapleader = ','

" Disable arrow keys
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>

" F2 makes pasting the clipboard preserve indentation
" F2 again turns that off.
nnoremap <F2> :set invpaste paste?<CR>
imap <F2> <C-O><F2>
set pastetoggle=<F2>

" Window navigation
map <c-l> <c-w>l
map <c-h> <c-w>h
map <c-j> <c-w>j
map <c-k> <c-w>k

" Toggle NERDTree window
map <leader>n :NERDTreeToggle<CR>

" Open NERDTree to the current directory
map <leader>f :NERDTreeFind<CR>

" Stamp last yanked text over current word
nnoremap <leader>s "_diwP

" Clear search matches
nnoremap <leader><space> :noh<cr>

" Alias :w, :q
command WQ wq
command Wq wq
command W w
command Q q

if &term =~ '256color'
    " Disable Background Color Erase (BCE) so that color schemes
    " work properly when Vim is used inside tmux and GNU screen.
    " See also http://snk.tuxfamily.org/log/vim-256color-bce.html
    set t_ut=
endif

" Source the vimrc file after saving it
if has("autocmd")
  autocmd bufwritepost .vimrc source $MYVIMRC
endif

" Load a local vimrc if available
if filereadable(expand("~/.vimrc.local"))
  source ~/.vimrc.local
endif

