#!/bin/bash

run_help() {

cat <<EOT

OS X dotfiles - Nicolas Gallagher - http://nicolasgallagher.com/

Usage: $(basename "$0") [options]

Options:
    --no-brew       Suppress attempts to update/install Homebrew
    --no-update     Suppress pulling from the remote repository

Copyright (c) Nicolas Gallagher
Licensed under the MIT license."
EOT

}
