#!/bin/bash

# Additional bash configuration which is specific to OS X

# Amend $PATH
gnubin="$(brew --prefix coreutils)/libexec/gnubin"
if [ -d ${gnubin} ]; then
    PATH="$PATH:${gnubin}"
    export PATH
fi
unset gnubin

# See if we can source Homebrew's bash completion
bash_completion_path="$(brew --prefix)/etc/bash_completion"

# Source Bash completion (installed via Homebrew)
if [[ -r $bash_completion_path ]]; then
    source $bash_completion_path
fi

# Local IP address
alias localip="ipconfig getifaddr en1"

# Copy my public key to my clipboard
alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | printf '=> Public key copied to pasteboard.\n'"

# Also, clear Apple’s System Logs to improve shell startup speed
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl"

# Recursively delete `.DS_Store` files
alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"
