#!/bin/bash

# Additional bash configuration which is specific to OS X

# See if we can source Homebrew's bash completion
bash_completion_path="$(brew --prefix)/etc/bash_completion"

# Source Bash completion (installed via Homebrew)
if [[ -r $bash_completion_path ]]; then
    source $bash_completion_path
fi

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en1"

# Copy my public key to my clipboard
alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | printf '=> Public key copied to pasteboard.\n'"

# Also, clear Apple’s System Logs to improve shell startup speed
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl"

# Recursively delete `.DS_Store` files
alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"
